using System.Globalization;
using System.IO;
using System.Security.Cryptography;
using Microsoft.Extensions.DependencyInjection;
using PrintFlow.App.Composition;
using PrintFlow.Domain.Attempts;
using PrintFlow.Domain.Files;
using PrintFlow.Domain.Ids;
using PrintFlow.Domain.Outputs;
using PrintFlow.Domain.Results;
using PrintFlow.Domain.Revisions;
using PrintFlow.Domain.Sessions;
using PrintFlow.Infrastructure.Adapters.Photoshop;
using PrintFlow.Infrastructure.Configuration;
using PrintFlow.Infrastructure.Sqlite;
using PrintFlow.Infrastructure.Workspace;
using PrintFlow.Tests.Fixtures;
using PrintFlow.Workflow.Commands;
using PrintFlow.Workflow.Engine;
using PrintFlow.Workflow.Ports;
using PrintFlow.Workflow.Services;
using Xunit.Abstractions;

namespace PrintFlow.Tests.Smoke;

/// <summary>
/// The live proof of the visual-only input contract that superseded SCRUM-11101: a customer PSD
/// carrying its own white-ink spot channel is prepared as ordinary visual artwork, and the white
/// ink in the production TIFF is generated by PrintFlow's validated Action rather than kept from
/// the source.
/// </summary>
/// <remarks>
/// The fixture is what makes this decidable. <see cref="SpotChannelPsdFixtures.QuadrantW1Psd"/>
/// carries one <c>W1</c> spot channel whose ink is an asymmetric four-quadrant pattern —
/// 0 / 96 / 192 / 255 — so one whole quadrant carries no ink at all and the channel covers exactly
/// 75% of the canvas. A W1 generated from the opaque composite covers essentially all of it. "The
/// TIFF has a W1" would be true either way; the coverage says which one it is.
/// <para>
/// Two tests, because each guarded open drives the real application to the foreground and two of
/// them in one run compete for it — the same reason the other workstation smokes are split.
/// </para>
/// <para>
/// Opt in with <c>PRINTFLOW_VISUAL_ONLY_W1_SMOKE=1</c>.
/// </para>
/// </remarks>
public sealed class VisualOnlyProductionWhiteInkSmoke(ITestOutputHelper output)
{
    private const string EnableVariable = "PRINTFLOW_VISUAL_ONLY_W1_SMOKE";

    /// <summary>
    /// Through the real Product path: a supported PSD carrying an existing W1 spot channel is
    /// prepared into a managed visual raster and offered for review, with no refusal and no
    /// operator decision anywhere.
    /// </summary>
    [Fact]
    public async Task Psd_carrying_existing_W1_prepares_as_ordinary_visual_artwork()
    {
        if (Environment.GetEnvironmentVariable(EnableVariable) != "1") return;

        PrintFlowConfiguration configuration = PrintFlowConfiguration.LoadFromFile(
            RepositoryFile("appsettings.json"));
        configuration.Adapters.Mode.ShouldBe("Production");

        string token = Token();
        string qa = Path.Combine(configuration.Workspace.Root, "Evidence", "SCRUM-11101-VISUAL-" + token);
        Directory.CreateDirectory(qa);
        output.WriteLine("Evidence workspace   : " + qa);

        SqliteConnectionFactory factory = new(Path.Combine(qa, "visual-only.db"));
        using (var connection = factory.Open()) MigrationRunner.Migrate(connection).IsSuccess.ShouldBeTrue();
        using var provider = ServiceRegistration.BuildServiceProvider(
            configuration, configuration.Workspace.Root, factory);

        var gate = provider.GetRequiredService<IEnvironmentGate>().Verify(AdapterExecutionMode.Production);
        gate.IsSuccess.ShouldBeTrue(gate.IsFailure ? gate.Failure.ToString() : "");

        var processor = provider.GetRequiredService<IPhotoshopOutputProcessor>()
            .ShouldBeOfType<ProductionPhotoshopOutputProcessor>();
        var before = await processor.EnsureReadyAsync(CancellationToken.None);
        before.IsSuccess.ShouldBeTrue(before.IsFailure ? before.Failure.ToString() : "");
        output.WriteLine("Photoshop before     : " + before.Value.State.State);

        byte[] bytes = SpotChannelPsdFixtures.QuadrantW1Psd();
        string source = Path.Combine(qa, "PF_11101_VISUAL_W1.psd");
        File.WriteAllBytes(source, bytes);
        string sourceShaBefore = Convert.ToHexString(SHA256.HashData(bytes));
        output.WriteLine("source SHA-256 before: " + sourceShaBefore);

        var service = provider.GetRequiredService<ISessionService>();
        var repository = provider.GetRequiredService<ISessionRepository>();
        var imported = await service.ImportAsync(
            WorkflowType.GeneratePrintTiff, source, null, "synthetic-qa", CancellationToken.None);
        imported.IsSuccess.ShouldBeTrue();
        output.WriteLine("Session              : " + imported.Value.Id);

        var prepared = await service.ExecuteAsync(
            imported.Value.Id, new WorkflowCommand.StartStep(StepKind.OriginalConfirmation),
            "synthetic-qa", CancellationToken.None);
        output.WriteLine("Preparation          : " +
            (prepared.IsSuccess ? "SUCCEEDED" : prepared.Failure.ToString()));

        // The superseded behaviour refused here with PsdUnsupported, on nothing but the presence
        // of the spot channel. A PSD is a visual design input, so it prepares.
        prepared.IsSuccess.ShouldBeTrue(prepared.IsFailure ? prepared.Failure.ToString() : "");

        SessionAggregate stored = (await repository.LoadAsync(imported.Value.Id, CancellationToken.None)).Value!;
        Revision raster = stored.Revisions.Single(r => r.Operation == OperationKind.PreparePsd);
        string rasterPath = provider.GetRequiredService<IWorkspace>().ResolveAbsolute(raster.File);

        raster.Facts.Format.ShouldBe(ImageFormat.Png);
        raster.Facts.ColourMode.ShouldBe(ColourMode.Rgb);
        raster.Facts.PixelWidth.ShouldBe(SpotChannelPsdFixtures.Width);
        raster.Facts.PixelHeight.ShouldBe(SpotChannelPsdFixtures.Height);
        output.WriteLine($"managed raster       : {raster.File.RelativePath} " +
                         $"({raster.Facts.PixelWidth}x{raster.Facts.PixelHeight} {raster.Facts.Format}/{raster.Facts.ColourMode})");

        // PNG colour type 2 or 6 at 8 bits: RGB, or RGB with alpha, and nothing else. There is no
        // representation of a spot channel in the artefact the operator reviews, so no source ink
        // identity can travel downstream from here.
        byte[] header = new byte[26];
        using (FileStream stream = File.OpenRead(rasterPath)) stream.ReadExactly(header);
        header[24].ShouldBe((byte)8);
        header[25].ShouldBeOneOf((byte)2, (byte)6);
        output.WriteLine($"PNG colour type      : {header[25]} at {header[24]} bits — no spot channel exists in PNG");

        // The observation is still recorded, as a diagnostic. It is simply not authority.
        ProcessingAttempt attempt = stored.Attempts.Single(a => a.Operation == OperationKind.PreparePsd);
        attempt.Status.ShouldBe(AttemptStatus.Succeeded);
        PsdInspection inspection = attempt.PsdInspection.ShouldNotBeNull();
        inspection.HasW1.ShouldBeTrue("the source really did carry a W1, or this proves nothing");
        inspection.HasSpots.ShouldBeTrue();
        output.WriteLine("persisted inspection : HasW1=true, HasSpots=true (diagnostics only, no authority)");
        output.WriteLine("channels observed    : " +
            string.Join(", ", inspection.Channels.Select(c => $"{c.Name}/{c.Kind}")));

        // The operator is offered review, and is offered no white-ink decision of any kind.
        WorkflowSnapshot snapshot = stored.ToSnapshot();
        snapshot.CurrentStep!.Step.ShouldBe(StepKind.OriginalConfirmation);
        snapshot.CurrentStep!.State.ShouldBe(StepState.ReviewRequired);
        output.WriteLine("step state           : " + snapshot.CurrentStep!.State);

        SessionView view = (await service.LoadAsync(imported.Value.Id, CancellationToken.None)).Value!;
        view.AvailableCommands.Select(command => command.ToString())
            .ShouldNotContain(name => name.Contains("Retain", StringComparison.OrdinalIgnoreCase) ||
                                      name.Contains("WhiteInk", StringComparison.OrdinalIgnoreCase));
        output.WriteLine("available commands   : " + string.Join(", ", view.AvailableCommands));

        // The customer's file is untouched, as on every other path.
        string sourceShaAfter = Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(source)));
        sourceShaAfter.ShouldBe(sourceShaBefore);
        output.WriteLine("source SHA-256 after : " + sourceShaAfter + "  (unchanged)");

        var after = await processor.EnsureReadyAsync(CancellationToken.None);
        after.IsSuccess.ShouldBeTrue(after.IsFailure ? after.Failure.ToString() : "");
        output.WriteLine("Photoshop after      : " + after.Value.State.State);
    }

    /// <summary>
    /// The white ink in the production TIFF made from a PSD-with-W1's approved visual raster is
    /// the one PrintFlow generated, not the one the customer's file arrived with.
    /// </summary>
    /// <remarks>
    /// The join point is the managed PNG, which is exactly what the Product's Photoshop Output
    /// step resolves through the step lineage. Everything below that point is the accepted output
    /// chain, driven exactly as <c>PhotoshopTiffWorkstationSmoke</c> drives it, and none of it
    /// knows the source was a PSD at all.
    /// </remarks>
    [Fact]
    public async Task Production_TIFF_white_ink_is_generated_not_carried_over_from_the_source_psd()
    {
        if (Environment.GetEnvironmentVariable(EnableVariable) != "1") return;

        PrintFlowConfiguration configuration = PrintFlowConfiguration.LoadFromFile(
            RepositoryFile("appsettings.json"));
        configuration.Adapters.Mode.ShouldBe("Production");

        string token = Token();
        string qa = Path.Combine(configuration.Workspace.Root, "Evidence", "SCRUM-11101-TIFF-" + token);
        Directory.CreateDirectory(qa);
        output.WriteLine("Evidence workspace   : " + qa);

        // ------------------------------------------------------------------------------
        // 1. The real Product PSD path, producing the approved visual raster.
        // ------------------------------------------------------------------------------
        SqliteConnectionFactory factory = new(Path.Combine(qa, "visual-only-tiff.db"));
        using (var connection = factory.Open()) MigrationRunner.Migrate(connection).IsSuccess.ShouldBeTrue();
        using var provider = ServiceRegistration.BuildServiceProvider(
            configuration, configuration.Workspace.Root, factory);
        provider.GetRequiredService<IEnvironmentGate>().Verify(AdapterExecutionMode.Production)
            .IsSuccess.ShouldBeTrue();

        byte[] bytes = SpotChannelPsdFixtures.QuadrantW1Psd();
        string source = Path.Combine(qa, "PF_11101_TIFF_W1.psd");
        File.WriteAllBytes(source, bytes);
        string sourceShaBefore = Convert.ToHexString(SHA256.HashData(bytes));

        var service = provider.GetRequiredService<ISessionService>();
        var imported = await service.ImportAsync(
            WorkflowType.GeneratePrintTiff, source, null, "synthetic-qa", CancellationToken.None);
        imported.IsSuccess.ShouldBeTrue();
        var preparedStep = await service.ExecuteAsync(
            imported.Value.Id, new WorkflowCommand.StartStep(StepKind.OriginalConfirmation),
            "synthetic-qa", CancellationToken.None);
        preparedStep.IsSuccess.ShouldBeTrue(preparedStep.IsFailure ? preparedStep.Failure.ToString() : "");

        SessionAggregate stored = (await provider.GetRequiredService<ISessionRepository>()
            .LoadAsync(imported.Value.Id, CancellationToken.None)).Value!;
        Revision approved = stored.Revisions.Single(r => r.Operation == OperationKind.PreparePsd);
        string approvedPath = provider.GetRequiredService<IWorkspace>().ResolveAbsolute(approved.File);
        output.WriteLine($"approved raster      : {approved.Facts.PixelWidth}x{approved.Facts.PixelHeight} " +
                         $"{approved.Facts.Format}/{approved.Facts.ColourMode}");

        // The source W1 covered exactly 75% of the canvas. Nothing in the raster carries it.
        output.WriteLine($"source W1 coverage   : 75.00% (quadrant pattern {string.Join('/',
            SpotChannelPsdFixtures.QuadrantInk)}), present in the PSD and in no later artefact");

        // ------------------------------------------------------------------------------
        // 2. The accepted production output chain, on the approved visual raster.
        // ------------------------------------------------------------------------------
        string root = Path.Combine(configuration.Workspace.Root, "QA", "Scrum11101Visual", token);
        FileWorkspace workspace = new(root);
        IPhotoshopTiffAutomation automation = PhotoshopAutomationComposition.CreateTiffAutomation(
            Path.Combine(configuration.Workspace.Root, configuration.Preset.Path),
            Sha256.Parse(configuration.Preset.ExpectedSha256), workspace,
            Path.Combine(root, "Evidence"), TimeProvider.System);

        WorkspaceFileRef managed = WorkspaceFileRef.Create(
            $"Sessions/S_11101V/Working/A_{token}/PF_11101_APPROVED_{token}.png", WorkspaceArea.Working);
        string managedPath = workspace.ResolveAbsolute(managed);
        Directory.CreateDirectory(Path.GetDirectoryName(managedPath)!);
        File.Copy(approvedPath, managedPath);
        Sha256 backing = Sha256.FromBytes(SHA256.HashData(File.ReadAllBytes(managedPath)));

        // Photoshop has just been driven through a whole PSD preparation and must be back in an
        // accepted clean starting state before the output chain opens its own document. This is
        // the Product's own readiness gate — the same one SessionService takes between steps —
        // not a wait inserted to make the test pass.
        var between = await automation.EnsureReadyAsync(CancellationToken.None);
        between.IsSuccess.ShouldBeTrue(between.IsFailure ? between.Failure.ToString() : "");
        between.Value.State.State.ShouldBeOneOf(
            PhotoshopStartingState.KnownStartScreen, PhotoshopStartingState.KnownEditorNoDocument);
        output.WriteLine("Photoshop between    : " + between.Value.State.State);

        PrintDimensions dimensions = PrintDimensions.FromMillimetres(50, 40, SizePreset.Custom);
        FitWithinBoundsPreparation preparation = new(PrintPreparationPlan.For(
            new RevisionId(Guid.CreateVersion7()), backing,
            approved.Facts.PixelWidth!.Value, approved.Facts.PixelHeight!.Value, dimensions));

        var opened = await automation.OpenManagedWorkingFileAsync(managed, CancellationToken.None);
        opened.IsSuccess.ShouldBeTrue(opened.IsFailure ? opened.Failure.ToString() : "");
        try
        {
            var sized = await automation.PrepareDocumentAsync(
                opened.Value, preparation, CancellationToken.None);
            if (sized.IsFailure) output.WriteLine("prepare failure      : " + sized.Failure);
            sized.IsSuccess.ShouldBeTrue(sized.IsFailure ? sized.Failure.ToString() : "");
            output.WriteLine($"sized for production : {sized.Value.Actual.PixelWidth}x{sized.Value.Actual.PixelHeight} " +
                             $"@ {sized.Value.Actual.ResolutionPpi} PPI, {sized.Value.Actual.ColourMode}");

            // GuardedPhotoshopW1Executor refuses outright if the document already carries a W1 or
            // any spot channel. That it runs at all is itself proof that no source ink got here.
            var w1 = await automation.ExecuteW1Async(
                opened.Value, sized.Value, WhiteUnderbaseBranch.W1_1px, CancellationToken.None);
            if (w1.IsFailure) output.WriteLine("W1 failure           : " + w1.Failure);
            w1.IsSuccess.ShouldBeTrue(w1.IsFailure ? w1.Failure.ToString() : "");
            w1.Value.ActionInvocationOccurredExactlyOnce.ShouldBeTrue();
            output.WriteLine($"validated Action     : {w1.Value.ActionSetName} / {w1.Value.ActionName} " +
                             $"(branch {w1.Value.Branch}), invoked exactly once");

            WorkspaceFileRef tiff = WorkspaceFileRef.Create(
                managed.RelativePath[..^managed.FileName.Length] + $"PRINT_50mm_CMYK_W_{token}.tif",
                WorkspaceArea.Working);
            var saved = await automation.SaveProductionTiffAsync(
                opened.Value, w1.Value, tiff, CancellationToken.None);
            if (saved.IsFailure) output.WriteLine("TIFF failure         : " + saved.Failure);
            saved.IsSuccess.ShouldBeTrue(saved.IsFailure ? saved.Failure.ToString() : "");

            ProductionTiffFacts facts = saved.Value.Facts;
            output.WriteLine($"TIFF                 : {facts.PixelWidth}x{facts.PixelHeight} @ " +
                             $"{facts.XResolutionDpi:R} DPI, samples={facts.SamplesPerPixel}, " +
                             $"names={string.Join(',', facts.ExtraChannelNames)}, " +
                             $"spot={facts.W1IsPhotoshopSpotChannel}, nonWhite={facts.W1NonWhiteSampleCount}");

            facts.SamplesPerPixel.ShouldBe((ushort)5);
            facts.ExtraSamples.ShouldBe([(ushort)0]);
            facts.ExtraChannelNames.ShouldBe(["W1"]);
            facts.W1IsPhotoshopSpotChannel.ShouldBeTrue();
            facts.XResolutionDpi.ShouldBe(300, 0.0001);
            saved.Value.SaveSettings.ShouldBe(PhotoshopProductionTiffSaveSettings.Accepted);

            // The distinguishing fact. A generated underbase is derived from the opaque composite
            // and covers essentially the whole canvas; the source W1 left one entire quadrant
            // blank and covered 75%. This W1 is PrintFlow's, not the customer's.
            double coverage = (double)facts.W1NonWhiteSampleCount /
                              ((long)facts.PixelWidth * facts.PixelHeight);
            output.WriteLine($"TIFF W1 coverage     : {coverage:P2}  " +
                             "(generated ~100%; a retained source W1 would read ~75%)");
            coverage.ShouldBeGreaterThan(0.95,
                "the TIFF W1 reproduces the source quadrant pattern, so source white ink was retained");

            File.ReadAllBytes(source).ShouldBe(bytes, "the customer PSD was modified");
            Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(source))).ShouldBe(sourceShaBefore);
            output.WriteLine("source SHA-256       : " + sourceShaBefore + "  (unchanged)");
        }
        finally
        {
            // A failure anywhere above must not leave the operator holding an open document.
            var closed = await automation.CloseExactDocumentAsync(
                opened.Value, managed, CancellationToken.None);
            output.WriteLine(closed.IsSuccess
                ? "document closed      : cleanly, through the accepted seam"
                : $"document close       : REFUSED — {closed.Failure.Code}: {closed.Failure.TechnicalDetail}");

            var ready = await automation.EnsureReadyAsync(CancellationToken.None);
            output.WriteLine("Photoshop after      : " + (ready.IsSuccess
                ? ready.Value.State.State.ToString()
                : ready.Failure.ToString()));
        }
    }

    private static string Token() =>
        DateTimeOffset.Now.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture) +
        "-" + Guid.NewGuid().ToString("N")[..8].ToUpperInvariant();

    private static string RepositoryFile(string relativePath)
    {
        DirectoryInfo? current = new(AppContext.BaseDirectory);
        while (current is not null && !File.Exists(Path.Combine(current.FullName, "PrintFlowStudio.sln")))
        {
            current = current.Parent;
        }

        current.ShouldNotBeNull("the repository root must be locatable from the test output.");
        return Path.Combine(current.FullName, relativePath);
    }
}
