using System.Collections.Immutable;

namespace PrintFlow.Domain.Files;

/// <summary>Facts observed by Photoshop, alongside the PSD's explicit compatibility flag.</summary>
public sealed record PsdInspection(
    int PixelWidth,
    int PixelHeight,
    string OriginalMode,
    int BitDepth,
    bool HasRealMergedData,
    bool? HasTransparency,
    ImmutableArray<PsdChannel> Channels,
    string PhotoshopVersion)
{
    /// <summary>Diagnostics only: the source PSD declared at least one spot channel.</summary>
    /// <remarks>
    /// This and <see cref="HasW1"/> record what Photoshop saw in the customer's design file. They
    /// are deliberately not consulted by any preparation, validation or output rule: a PSD is a
    /// visual design input, so its spot and white-ink channels are rasterised out with every other
    /// non-component channel and never become production authority. Production W1 is generated by
    /// the signed Action immediately before the TIFF is written. Preserving the observation is
    /// still worth it — an operator asking why a file looked different in Photoshop can be told
    /// that it carried spot ink.
    /// </remarks>
    public bool HasSpots => Channels.Any(c => c.Kind == "SPOTCOLOR");

    /// <summary>Diagnostics only: the source PSD declared a channel named <c>W1</c>.</summary>
    /// <remarks>See <see cref="HasSpots"/>. This is never a refusal reason and never an authority.</remarks>
    public bool HasW1 => Channels.Any(c => string.Equals(c.Name, "W1", StringComparison.OrdinalIgnoreCase));
}

public sealed record PsdChannel(string Name, string Kind);
