using System.Collections.Immutable;
using PrintFlow.Domain.Files;
using PrintFlow.Domain.Outputs;
using PrintFlow.Domain.Results;

namespace PrintFlow.Infrastructure.Adapters.Photoshop;

/// <summary>Factual properties of the one W1 channel returned by Photoshop.</summary>
public sealed record PhotoshopW1ChannelFacts(
    string Name,
    string Type,
    bool IsNonEmpty,
    long NonWhitePixelCount,
    double? SolidityPercent,
    ImmutableArray<double> SpotColourComponents);

/// <summary>
/// The factual in-memory CMYK + W1 result. It is not an AdapterOutput, PrintOutput or Revision.
/// </summary>
/// <remarks>
/// <see cref="Branch"/>, <see cref="ActionSetName"/>, <see cref="ActionName"/> and
/// <see cref="ActionInvocationOccurredExactlyOnce"/> together carry the production white-ink
/// invariant: every W1 this Product can put into a TIFF was created here, by the signed
/// production Action, invoked exactly once on this document. They are true of every prepared
/// document the Product can produce, and that is the point — the type has no way to express white
/// ink from anywhere else, so no caller can introduce one.
/// <para>
/// SCRUM-11101-A briefly modelled this as an open <c>Provenance</c> choice between generated and
/// <i>retained</i> white ink, because the original SCRUM-11101 acceptance criterion let an
/// operator keep the white ink a customer's PSD arrived with. The business contract that
/// superseded SCRUM-11101 makes PSD and PDF visual-only design inputs: source spot and white-ink
/// channels never become production channels, and production W1 is always generated by PrintFlow
/// immediately before the TIFF is written. Retained white ink is therefore not a case that can
/// occur, and the flat members are once again the honest model. See
/// <c>docs/printflow/scrum-11101-existing-white-ink-decision.md</c>.
/// </para>
/// </remarks>
public sealed record PhotoshopW1PreparedDocument(
    string DocumentFullPath,
    int PixelWidth,
    int PixelHeight,
    double ResolutionPpi,
    double PhysicalWidthMm,
    double PhysicalHeightMm,
    string ColourMode,
    string BitDepth,
    ImmutableArray<PhotoshopChannelFact> ProcessChannels,
    PhotoshopW1ChannelFacts W1,
    WhiteUnderbaseBranch Branch,
    string ActionSetName,
    string ActionName,
    bool OtherDocumentsMayBeOpen,
    Sha256 BackingWorkingSha256,
    bool ActionInvocationOccurredExactlyOnce);

/// <summary>
/// The closed Infrastructure-only CMYK + W1 operation. The only caller-selected action input is
/// <see cref="WhiteUnderbaseBranch"/>; set names, action names and script are verified evidence.
/// </summary>
public interface IPhotoshopW1Automation : IPhotoshopPreparationAutomation
{
    Task<OperationResult<PhotoshopW1PreparedDocument>> ExecuteW1Async(
        PhotoshopOpenedDocument opened,
        PhotoshopPreparedDocument prepared,
        WhiteUnderbaseBranch branch,
        CancellationToken cancellationToken);
}
